name: AI PR Review

# The pull_request_target is an important feature. It is running on files from `main`.
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - 'main'

jobs:
  ai-code-review:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref, 'dependabot') }}

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: 'npm'

      - name: Install dependencies
        run: npm i gaunt-sloth-assistant@1.0.4 -g && gth --version

      - name: Extract issue number from PR title
        id: extract_issue
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          ISSUE_NUMBER=$(echo "$PR_TITLE" | grep -oE '^[0-9]{2,5} ' | tr -d ' ' || true)
          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT

      - name: Perform code review
        id: review
        continue-on-error: true
        run: |
          if [ -z "${{ steps.extract_issue.outputs.issue_number }}" ]; then
            echo "â„¹ï¸ **Tip:** To link this PR to an issue, start your PR title with the issue number followed by a space (e.g., '123 Fix authentication bug')" | tee review.md
            echo "" >> review.md
            gth --nopipe -i review pr ${{ github.event.pull_request.number }}
          else
            gth --nopipe -i review pr ${{ github.event.pull_request.number }} ${{ steps.extract_issue.outputs.issue_number }}
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}

      - name: Hide older AI review comments and post new one
        uses: actions/github-script@v8
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const review = fs.readFileSync('review.md', 'utf8');

            // Define a unique identifier for AI review comments
            const AI_REVIEW_IDENTIFIER = '<!-- AI-PR-REVIEW-BOT -->';

            // Get all comments on this PR
            const comments = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
            });

            // Find and hide older AI review comments
            const aiComments = comments.data.filter(comment =>
              comment.user.login === 'github-actions[bot]' &&
              comment.body.includes(AI_REVIEW_IDENTIFIER)
            );

            // Hide older comments by wrapping them in a collapsible section
            for (const comment of aiComments) {
              const hiddenBody = `<details>
            <summary>ðŸ¤– Previous AI Review (Click to expand)</summary>

            ${comment.body}
            </details>`;

              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment.id,
                body: hiddenBody
              });
            }

            // Create new comment with the identifier
            const newCommentBody = `${AI_REVIEW_IDENTIFIER}

            ${review}`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: newCommentBody
            });

      - name: Check review step result
        if: steps.review.outcome == 'failure'
        run: |
          echo "Code review step failed with exit code 1"
          exit 1
